---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install openssh
  apt:
    name: openssh-server
    state: present

- name: Ensure openssh service is running
  service:
    name: ssh
    state: started
