- name: Forward port 80 to http_server_port
  vars:
    ansible_become: yes
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: "{{ http_server_port }}"
    comment: Redirect web traffic to port {{ http_server_port }}

- name: Save current state of the firewall in system file
  vars:
    ansible_become: yes
  community.general.iptables_state:
    state: saved
    path: /etc/sysconfig/iptables
