---
- name: Install the gpg key for nodejs LTS
  vars:
    ansible_become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
                                        
- name: Install the nodejs LTS repos
  vars:
    ansible_become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  vars:
    ansible_become: yes
  apt:
    name: nodejs
    state: present

- name: Install "http-server" node.js package globally.
  vars:
    ansible_become: yes
  community.general.npm:
    name: http-server
    global: yes
